### ISSUE TITLE
Error 804: forward compatibility was attempted on non supported HW

### ISSUE THREAD

**Issue by betterthanever2** [Haidra-Org/horde-worker-reGen#349]
I'm trying to set up a worker on my home PC. GPU is GeForce RTX 4070. When setting up, I went with `moderate_performance_mode` as suggested in the guide. Also: I'm using Docker-based setup.

When starting the container, I'm getting `RuntimeError: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW`

Full text of the error:
```
reGen  | 2024-11-16 13:46:25.069 | DEBUG    | horde_worker_regen.load_env_vars:load_env_vars_from_config:68 - Using default AI Horde URL.
reGen  | 2024-11-16 13:46:25.096 | DEBUG    | horde_sdk:_dev_env_var_warnings:44 - AIWORKER_CACHE_HOME is ./models/.
reGen  | 2024-11-16 13:46:28.057 | DEBUG    | horde_model_reference.legacy.classes.legacy_converters:write_out_records:554 - Converted database written to: /horde-worker-reGen/models/horde_model_reference/stable_diffusion.json
reGen  | 2024-11-16 13:46:29.551 | DEBUG    | horde_model_reference.legacy.classes.legacy_converters:write_out_records:554 - Converted database written to: /horde-worker-reGen/models/horde_model_reference/stable_diffusion.json
reGen  | 2024-11-16 13:46:38.742 | WARNING  | horde_model_reference.model_reference_records:validator_is_style_known:132 - Unknown style control_qr for model control_qr
reGen  | 2024-11-16 13:46:38.742 | WARNING  | horde_model_reference.model_reference_records:validator_is_style_known:132 - Unknown style control_qr_xl for model control_qr_xl
reGen  | 2024-11-16 13:46:38.749 | DEBUG    | horde_sdk.ai_horde_worker.model_meta:remove_large_models:155 - Removing cascade models: {'Stable Cascade 1.0'}
reGen  | 2024-11-16 13:46:38.749 | DEBUG    | horde_sdk.ai_horde_worker.model_meta:remove_large_models:156 - Removing flux models: {'Flux.1-Schnell fp16 (Compact)', 'Flux.1-Schnell fp8 (Compact)'}
reGen  | /horde-worker-reGen/venv/lib/python3.11/site-packages/transformers/utils/hub.py:128: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
reGen  |   warnings.warn(
reGen  | /horde-worker-reGen/venv/lib/python3.11/site-packages/torch/cuda/__init__.py:129: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
reGen  |   return torch._C._cuda_getDeviceCount() > 0
reGen  | 2024-11-16 13:46:40.464 | INFO     | horde_safety.deep_danbooru_model:download_deep_danbooru_model:53 - Downloading DeepDanbooru model (~614 mb) to models/clip_blip/model-resnet_custom_v3.pt.
models/clip_blip/model-resnet_custom_v3.pt:   0% 0.00/644M [00:00<?, ?iB/s]2024-11-16 13:46:41.312 | INFO     | horde_safety.deep_danbooru_model:download_deep_danbooru_model:69 - Model already downloaded, but it is the wrong size. Redownloading.
models/clip_blip/model-resnet_custom_v3.pt: 100% 644M/644M [01:23<00:00, 7.76MiB/s] 
reGen  | 2024-11-16 13:48:04.323 | INFO     | horde_safety.deep_danbooru_model:verify_deep_danbooru_model_hash:30 - Verifying SHA256 hash of downloaded file.
reGen  | 2024-11-16 13:48:04.808 | INFO     | horde_safety.deep_danbooru_model:download_deep_danbooru_model:85 - Model downloaded successfully.
reGen  | Loading CLIP model ViT-L-14/openai...
open_clip_model.safetensors: 100% 1.71G/1.71G [02:33<00:00, 11.1MB/s]
reGen  | /horde-worker-reGen/venv/lib/python3.11/site-packages/open_clip/factory.py:372: UserWarning: These pretrained weights were trained with QuickGELU activation but the model config does not have that enabled. Consider using a model config with a "-quickgelu" suffix or enable with a flag.
reGen  |   warnings.warn(
ViT-L-14_openai_artists.safetensors: 100% 16.2M/16.2M [00:01<00:00, 11.1MB/s]
ViT-L-14_openai_flavors.safetensors: 100% 155M/155M [00:13<00:00, 11.2MB/s] 
ViT-L-14_openai_mediums.safetensors: 100% 146k/146k [00:00<00:00, 2.73MB/s]
ViT-L-14_openai_movements.safetensors: 100% 307k/307k [00:00<00:00, 3.84MB/s]
ViT-L-14_openai_trendings.safetensors: 100% 111k/111k [00:00<00:00, 2.33MB/s]
ViT-L-14_openai_negative.safetensors: 100% 63.2k/63.2k [00:00<00:00, 2.62MB/s]
reGen  | Loaded CLIP model and data in 175.88 seconds.
reGen  | 2024-11-16 13:51:00.747 | INFO     | hordelib.comfy_horde:do_comfy_import:216 - Forcing normal vram mode
reGen  | Traceback (most recent call last):
reGen  |   File "/horde-worker-reGen/download_models.py", line 25, in <module>
reGen  |     download_all_models(
reGen  |   File "/horde-worker-reGen/horde_worker_regen/download_models.py", line 58, in download_all_models
reGen  |     hordelib.initialise()
reGen  |   File "/horde-worker-reGen/venv/lib/python3.11/site-packages/hordelib/initialisation.py", line 81, in initialise
reGen  |     hordelib.comfy_horde.do_comfy_import(
reGen  |   File "/horde-worker-reGen/venv/lib/python3.11/site-packages/hordelib/comfy_horde.py", line 230, in do_comfy_import
reGen  |     import execution
reGen  |   File "/horde-worker-reGen/venv/lib/python3.11/site-packages/hordelib/_comfyui/execution.py", line 13, in <module>
reGen  |     import nodes
reGen  |   File "/horde-worker-reGen/venv/lib/python3.11/site-packages/hordelib/_comfyui/nodes.py", line 21, in <module>
reGen  |     import comfy.diffusers_load
reGen  |   File "/horde-worker-reGen/venv/lib/python3.11/site-packages/hordelib/_comfyui/comfy/diffusers_load.py", line 3, in <module>
reGen  |     import comfy.sd
reGen  |   File "/horde-worker-reGen/venv/lib/python3.11/site-packages/hordelib/_comfyui/comfy/sd.py", line 5, in <module>
reGen  |     from comfy import model_management
reGen  |   File "/horde-worker-reGen/venv/lib/python3.11/site-packages/hordelib/_comfyui/comfy/model_management.py", line 143, in <module>
reGen  |     total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
reGen  |                                   ^^^^^^^^^^^^^^^^^^
reGen  |   File "/horde-worker-reGen/venv/lib/python3.11/site-packages/hordelib/_comfyui/comfy/model_management.py", line 112, in get_torch_device
reGen  |     return torch.device(torch.cuda.current_device())
reGen  |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
reGen  |   File "/horde-worker-reGen/venv/lib/python3.11/site-packages/torch/cuda/__init__.py", line 940, in current_device
reGen  |     _lazy_init()
reGen  |   File "/horde-worker-reGen/venv/lib/python3.11/site-packages/torch/cuda/__init__.py", line 319, in _lazy_init
reGen  |     torch._C._cuda_init()
reGen  | RuntimeError: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW
reGen exited with code 1
```

Am I doing something wrong here?

**Comment by tazlin** [comment]
I believe this is the error you get if the host machine does not have at least the driver and/or CUDA version support required by the container image. The default requirement is CUDA 12.4. You can either lower the container version used (see the docker readme for that) or you can update the drivers and CUDA version on the host machine.

If this doesn't fix it, or there is something unclear in what I'm saying, let me know and we can dig into it more.

**Comment by tazlin** [comment]
Glad to hear it. I will update the documentation to warn future users of the regen docker image to this pitfall.
